// <auto-generated />
using System;
using FleetTracking.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FleetTracking.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260105143429_INIT")]
    partial class INIT
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FleetTracking.Core.Entites.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double?>("LastHeading")
                        .HasColumnType("float");

                    b.Property<double?>("LastLatitude")
                        .HasColumnType("float");

                    b.Property<double?>("LastLongitude")
                        .HasColumnType("float");

                    b.Property<double?>("LastSpeed")
                        .HasColumnType("float");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("LastUpdatedAt");

                    b.HasIndex("PlateNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            DriverName = "أحمد محمد",
                            IsActive = true,
                            IsDeleted = false,
                            LastHeading = 90.0,
                            LastLatitude = 30.0444,
                            LastLongitude = 31.235700000000001,
                            LastSpeed = 65.5,
                            LastUpdatedAt = new DateTime(2025, 12, 31, 23, 58, 0, 0, DateTimeKind.Utc),
                            PlateNumber = "أ ب ج 1234",
                            Status = 1,
                            UpdatedAt = new DateTime(2025, 12, 31, 23, 58, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            DriverName = "محمود علي",
                            IsActive = true,
                            IsDeleted = false,
                            LastHeading = 45.0,
                            LastLatitude = 30.0626,
                            LastLongitude = 31.354700000000001,
                            LastSpeed = 0.0,
                            LastUpdatedAt = new DateTime(2025, 12, 31, 23, 57, 0, 0, DateTimeKind.Utc),
                            PlateNumber = "د هـ و 5678",
                            Status = 2,
                            UpdatedAt = new DateTime(2025, 12, 31, 23, 57, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DriverName = "خالد حسن",
                            IsActive = true,
                            IsDeleted = false,
                            LastHeading = 180.0,
                            LastLatitude = 31.200099999999999,
                            LastLongitude = 29.918700000000001,
                            LastSpeed = 0.0,
                            LastUpdatedAt = new DateTime(2025, 12, 31, 23, 52, 0, 0, DateTimeKind.Utc),
                            PlateNumber = "ز ح ط 9012",
                            Status = 3,
                            UpdatedAt = new DateTime(2025, 12, 31, 23, 52, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 12, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            DriverName = "عمر سعيد",
                            IsActive = true,
                            IsDeleted = false,
                            LastHeading = 270.0,
                            LastLatitude = 26.820599999999999,
                            LastLongitude = 30.802499999999998,
                            LastSpeed = 0.0,
                            LastUpdatedAt = new DateTime(2025, 12, 31, 23, 45, 0, 0, DateTimeKind.Utc),
                            PlateNumber = "ي ك ل 3456",
                            Status = 4,
                            UpdatedAt = new DateTime(2025, 12, 31, 23, 45, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 12, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            DriverName = "يوسف إبراهيم",
                            IsActive = true,
                            IsDeleted = false,
                            LastHeading = 315.0,
                            LastLatitude = 30.5852,
                            LastLongitude = 30.9922,
                            LastSpeed = 110.0,
                            LastUpdatedAt = new DateTime(2025, 12, 31, 23, 59, 0, 0, DateTimeKind.Utc),
                            PlateNumber = "م ن س 7890",
                            Status = 1,
                            UpdatedAt = new DateTime(2025, 12, 31, 23, 59, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 12, 31, 22, 0, 0, 0, DateTimeKind.Utc),
                            DriverName = "حسن عبدالله",
                            IsActive = true,
                            IsDeleted = false,
                            PlateNumber = "ع ف ص 2468",
                            Status = 4,
                            UpdatedAt = new DateTime(2025, 12, 31, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 12, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            DriverName = "مصطفى أحمد",
                            IsActive = true,
                            IsDeleted = false,
                            LastHeading = 0.0,
                            LastLatitude = 25.687200000000001,
                            LastLongitude = 32.639600000000002,
                            LastSpeed = 45.0,
                            LastUpdatedAt = new DateTime(2025, 12, 31, 23, 55, 0, 0, DateTimeKind.Utc),
                            PlateNumber = "ق ر ش 1357",
                            Status = 1,
                            UpdatedAt = new DateTime(2025, 12, 31, 23, 55, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            DriverName = "سامي وليد",
                            IsActive = false,
                            IsDeleted = false,
                            LastHeading = 0.0,
                            LastLatitude = 30.0444,
                            LastLongitude = 31.235700000000001,
                            LastSpeed = 0.0,
                            LastUpdatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            PlateNumber = "ت ث خ 9753",
                            Status = 4,
                            UpdatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 12, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            DriverName = "طارق فتحي",
                            IsActive = true,
                            IsDeleted = false,
                            LastHeading = 270.0,
                            LastLatitude = 31.040900000000001,
                            LastLongitude = 28.9617,
                            LastSpeed = 75.0,
                            LastUpdatedAt = new DateTime(2025, 12, 31, 23, 59, 30, 0, DateTimeKind.Utc),
                            PlateNumber = "ذ ض ظ 8642",
                            Status = 1,
                            UpdatedAt = new DateTime(2025, 12, 31, 23, 59, 30, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DriverName = "وليد صلاح",
                            IsActive = true,
                            IsDeleted = false,
                            LastHeading = 135.0,
                            LastLatitude = 30.583300000000001,
                            LastLongitude = 32.2667,
                            LastSpeed = 55.0,
                            LastUpdatedAt = new DateTime(2025, 12, 31, 23, 56, 0, 0, DateTimeKind.Utc),
                            PlateNumber = "غ إ أ 7531",
                            Status = 1,
                            UpdatedAt = new DateTime(2025, 12, 31, 23, 56, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
